governance.md
=> Governance update 4 27 15

conferences.md, index.html
Also removed last year's conference
=> add F2F registration, compute doc

index.html
=> Add F2F 2018 agenda

conferences.md, index.html
Not sure if the [Telecommute] works without the page (forthcoming).
=> Add agenda

esgf-compute-announcement.md, index.html
Add the announcement requested by @doutriaux1
=> Add ESGF Compute Release Announcement with link on front page

releases.md, videos.md
Holly released the videos to YouTube so we should link them here.
=> For now add the videos and update the release page

mailing-list.md
=> Remove outdated social media links, and add new YouTube link.

_includes/maintenance_banner.html, _includes/topbar.html, _layouts/default.html, _layouts/releases_sidebar.html
=> Add maintenance banner for website outage on October 4-6, 2019

2014-F2F.md, 2015-F2F.md, 2016-F2F.md, 2017-F2F.md, 2018-F2F.md, _layouts/releases_sidebar.html, acknowledgments.md, awards.md, developer-info.md, esgf-compute-announcement.md, federation-design.md, index.html, letters-of-recommendation.md, logo_requirements.md, mission.md, projects.md, publications.md, release1.2.md, release1.4.md, release1.5.md, release1.6.md, releases.md
Partially, if not completely, resolves issues #42 and #44. Updated 21 files with spelling and/or link fixes. Could not build the site locally, so hopefully everything looks OK (particularly release1.6.md). Let me know if you'd like me to adjust anything.
=> QA pass to fix spellings and links

committee.md
=> update X committee list and sort

2020-F2F.md
Updating the 2020 F2F page with a call for abstracts.
=> 2020 F2F Call for Abstracts

2020-F2F.md
@gabdulla
I have updated the 2020 ESGF F2F page with the info for registration.
=> Update registration information for the 2020 F2F

2020-F2F.md
@gabdulla @sashakames Updating abstract submission deadline to February 3.
=> Update 2020 F2F abstract submission deadline to February 3

index.html
Indicate events that were cancelled.
=> Mark events as cancelled

reports.md
Report hosted at https://esgf.llnl.gov/esgf-media/pdf/ESGF_Future_Architecture_Report.pdf
edit: Changed file name
=> Add ESGF Future Architecture Report

developer-info.md, software.md
=> Update software page

_layouts/default.html
=> Add VDP link to footer

_includes/hero.html, _includes/topbar.html, committee.md, nodes.md, releases.md, software.md, working-groups.md
Pushing Metagrid use to get more people to the beta test site.
=> updates include commitee lists and Metagrid

nodes.md, software.md
=> Ska metagrid - minor corrections

nodes.md
Add ORNL to the list of nodes.   Reorder alphabetically.  Mention CoG vs Metagrid UIs
=> reorder alpha-sort, add ORNL

esgf-technical-overview.md
Work in progress, still needs:
=> Technical overview page

_layouts/default.html
Use new [Vulnerability Disclosure Program](https://www.energy.gov/vulnerability-disclosure-policy) link.
=> Update VDP link

_includes/analytics.html, _layouts/default.html
=> Remove LLNL analytics and footer links
